### ISSUE TITLE
What's the difference from npm's zmq and zeromq? 

### ISSUE THREAD

**Issue by lucaszanella** [zeromq/zeromq.js#123]
I'm currently trying to run this example from the ZeroMQ guide: http://zguide.zeromq.org/js:taskvent
however, since I got this problem https://github.com/JustinTulloss/zeromq.node/issues/586 when doing `npm install zmq` I discovered this other zeromq nodejs binding, which seems like the official one. However, if it's official, why the guide examples require `zmq` and not `zeromq`? 

I tried to modify `require('zmq')` to `require('zeromq')` but I got this error:

```
require('tty').setRawMode(true);
               ^

TypeError: require(...).setRawMode is not a function

```

**Comment by rgbkrk** [comment]
The [source material for the zguide](https://github.com/booksbyus/zguide) now uses `zeromq` - we're [waiting on a new wikidot account](https://lists.zeromq.org/pipermail/zeromq-dev/2017-January/031296.html). /cc @sappo 

This version is based off of JustinTulloss/zeromq.node. We ship prebuilt binaries across (many) node and Electron versions to ease installation

What version of node are you on? `setRawMode` should be part of the `tty` module and the code sample there using `tty` is part of the example in zguide, not the code base here.

**Comment by lucaszanella** [comment]
@rgbkrk thanks, I removed tty and it worked with the original code from the guide, good to know that at least the official version installs with npm, because that one wasn't working. My node is v7.4.0

**Comment by sappo** [comment]
@rgbkrk I do have access to a the zguide wikidot site now. But I still require API access which is limited to pro accounts. I'll be in Brussels tomorrow and there I'll ask to Benjamin who has a pro account to deploy the most recent version.

**Comment by lucaszanella** [comment]
Ok, no problem, I changed zmq to zeromq and it's working fine (took off
that tty thing and the code worked). Thank you

Em 2 de fev de 2017 03:46, "Kevin Sapper" <notifications@github.com>
escreveu:

**Comment by AndreSteenveld** [comment]
Would a PR be appreciated documenting the answer to this question in the README.md or a FAQ?

**Comment by rgbkrk** [comment]
We would appreciate a PR documenting the answer to this question in the README or in an FAQ.

It would be possible to distribute the built binaries if the maintainers wanted to and had time. Many of our PRs languish there because of an inability to change org level CI/CD - appveyor, Travis, and GitHub hooks.

**Comment by stanleyxu2005** [comment]
I have the same question here. What is the benefit of switching from zmq to zeromq? More usable APIs? Better performance? I'd like to understand more. 

My current working environment has some problems of building zeromq, so it is still using zmq. If there is a good reason to switch, I will work hard to do a necessary upgrade.

**Comment by ronkorving** [comment]
Hi all,

I'm the core maintainer on `zmq`. I've recently not had any time to work on the module, and I was offered co-maintainership on the `zeromq` module. I want to transition to `zeromq`, away from `zmq`, because on `zmq` I can't edit the repo settings (while I maintain the project, the owner never gave me ownership). I can of course fork it to my own user account on GitHub, but if we have `zeromq/zeromq`, let's work together and move here :)

Some outstanding questions/issues:

- I don't know if `zeromq` is 100% on par with the commits of `zmq`.
- I have a huge WIP re-implementation sitting on the `zmq` repo which I would love to see land some day. It simplifies things a lot, and makes the API a lot more elegant imho. But it will require me to spend more time on it, which I currently unfortunately don't have.

**Comment by rgbkrk** [comment]
> on zmq I can't edit the repo settings (while I maintain the project, the owner never gave me ownership and is not responsive to requests)

That's certainly what made us start working on the prebuilt version on the nteract org originally, because we needed CI tooling that we could iterate on.

> let's work together and move here :)

Woohoo!

> I don't know if zeromq is 100% on par with the commits of zmq.

I think, at the very least, we're missing the fix related to monitoring of sockets.

> I have a huge WIP re-implementation PR sitting on the zmq repo which I would love to see land some day. It simplifies things a lot, and makes the API a lot more elegant imho. But it will require me to spend more time on it, which I currently unfortunately don't have.

My priority has been to make the current API work for our needs with jupyter kernels, which it does right now. At the same time, I think we should be able to make changes if people have time to do so. If there's not time, then it's likely to remain stagnant. I know that @minrk wanted to make some changes to the interface, though he wanted to figure out how far from the `zmq` we were going to go. It seems like effort can continue here now.

**Comment by cschar** [comment]
was just going through guide http://zguide.zeromq.org/js:hwclient

still using zmq there

**Comment by ronkorving** [comment]
@cschar Could you report that there?

**Comment by rolftimmermans** [comment]
With the 6.0 beta API changing massively it would be good to start an effort to update external examples wherever poossible. I have added this to #347 as an action after 6.0 is out of beta.
