### ISSUE TITLE
Add promises?

### ISSUE THREAD

**Issue by jez9999** [zeromq/zeromq.js#196]
Is this library going to get promise support?  It should be implemented.  I would like to be able to say, for example:

```
function doBind(socket: zmq.Socket) {
    socket
        .bind("tcp://1.2.3.4:8181")
        .then(function(data) {
            ...
        })
        .catch(function(err) {
            ...
        });
}
```

Yes, you can promisify stuff, but that breaks TypeScript because it only promisify's at runtime.  The correct way to fix it is to add promise implementation to the original library.

**Comment by rolftimmermans** [comment]
Recently I started work on a new implementation that solves a number of API issues with the current version of the library. All API methods are based on promises. It also includes TypeScript definitions. Please see [zeromq-ng](https://github.com/rolftimmermans/zeromq-ng).

Your feedback on the API would be helpful. My goal is to have it replace this library, or otherwise make it a production-ready viable alternative. Right now it mostly needs testing from users like you.

**Comment by jez9999** [comment]
@rolftimmermans How mature is it?  Not sure I want to use a beta library in my production code.  :-)  Also it's kind of annoying that it has to be a separate project; we already have `zmq` and `zeromq` for some reason, now a third? :-)

**Comment by rolftimmermans** [comment]
Well, I need your help to push it forward and maybe replace the current library. For now, maybe you can comment on the API, see what the impact on your project would be and run any test suite you may have with it?

**Comment by rgbkrk** [comment]
Also check out the discussion in #189 -- I'd say maintainers are generally in favor of it. I'll add some other comments there.

**Comment by rolftimmermans** [comment]
The latest 6.0 beta release incorporates all changes proposed in #189 and more. It would be great if you could try it out! The new version has an API that addresses some fundamental issues with the previous API, but it does include a compatibility layer that should make upgrading easier. 

If you run into any problems feel free to report it here or in a new issue.
