### ISSUE TITLE
how to install/rebuilt zeromq for Electron-3.0.0 ?

### ISSUE THREAD

**Issue by lianhub** [zeromq/zeromq.js#279]
I installed Electron-3.0.0 and found that zeromq is not working anymore.
Then I run:
      **npm rebuild zeromq --runtime=electron --target=3.0.0**
But it didn't solve the problem!

Anybody runs zeromq inside Electron-3.0.0 successfully?
Thanks!

**Comment by nikolovp** [comment]
It looks like the binding is abandoned. New versions have not been published for more than a year.

The last version v4.6.0 depends on prebuild-install v2.2.2, which depends on node-abi v2.0.0, which does not support electron v3 as target. You must manually bump node-abi to at least v2.4.4

**Comment by lianhub** [comment]
nikolovp, thanks for your answer!

So I just rolled back to Electron-v2, and zeromq works again.

**Comment by nikolovp** [comment]
Instead of rolling back to Electron v2, better fork the binding, update the *prebuild-install* dev dependency to its latest version and publish the module to a private npm registry (if you have one) or to npmjs.com (better namespace it like @lianhub/zeromq or similar to avoid collisions).

This is what I did so I can keep working with latest electron versions.

There is an open pull request for upgrading *prebuild-install* (https://github.com/zeromq/zeromq.js/pull/275) but there is no one to accept it.

**Comment by lianhub** [comment]
Hi nikolovp, I followed your instructions:
* Fork, and update prebuild-install dependency: 
https://github.com/lianhub/zeromq.js/blob/master/package.json
* publish as: https://www.npmjs.com/package/jerry-zeromq

But when I do "npm install jerry-zeromq --save-dev", I got WARNING:
`λ npm install

> jerry-zeromq@4.6.1 install D:\elec-test\plc-controller\node_modules\jerry-zeromq
> node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)


prebuild-install WARN install No prebuilt binaries found (target=8.11.4 runtime=node arch=x64 platform=win32)

Downloading libzmq for Windows
Download finished`
* And "jerry-zeromq" did NOT work.

Any hint? Thanks!

**Comment by rgbkrk** [comment]
The latest version of zeromq.js was shipped which includes binaries for electron 3. Upgrade to 5.0.0 when you get a chance. 😄

**Comment by nikolovp** [comment]
Cool, this will simplify our workflow.

I have one extra question. What is the reason for requiring msbuild toolset v140 instead of letting node-gyp pick the toolset based on msvs_version? It would be nice to be able to build the binding from source with VS above v2015 when a new electron versions gets published, instead of depending on prebuilt binaries.

**Comment by lianhub** [comment]
Thanks all you guys!
* I just upgraded to Electron-v3.0.2, and zeromq.js-v5.0.0
* Then run: npm rebuild zeromq --runtime=electron --target=3.0.2

And my program runs perfect as expected!!!

**Comment by lgeiger** [comment]
Cool, glad it works now

**Comment by absalonv** [comment]
I know this is closed, but @lgeiger or @rgbkrk does the same fix applies for Electron 4? I am currently having issues and seems like I'm not the [only one ](https://github.com/zeromq/zeromq.js/issues/302)

**Comment by aziotdev** [comment]
I am having the same issue with electron 6.0.2
