### ISSUE TITLE
npm install fails with Node.js v13.0.1

### ISSUE THREAD

**Issue by yunabe** [zeromq/zeromq.js#346]
## How to reproduce

Install `zeromq` by `npm install` with Node.js `v13.0.1`, which was released on `2019-10-22`.
I create a repository to show `npm install` fails with `v13.0.1` though it works perfectly with `v12.13.0`.

https://github.com/yunabe/zeromq.js.bug346

## What is expected

`zeromq` is installed successfully.

## Actual

The installation fails with messages like:

```
npm ERR! zeromq@5.1.1 install: `node scripts/prebuild-install.js || (node scripts/preinstall.js && node-gyp rebuild)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zeromq@5.1.1 install script.
```

**Comment by rolftimmermans** [comment]
The latest 6.0 beta release includes support for Node 13 and future versions (due to the magic of the new [ABI-stable API of Node.js](https://nodejs.org/api/n-api.html)). It would be great if you could try it out! The new version has a [new API](https://github.com/zeromq/zeromq.js#examples) that addresses some fundamental issues with the previous API, but it does include a [compatibility layer](https://github.com/zeromq/zeromq.js#compatibility-layer-for-version-45) that should make upgrading easier. See #189 for the reasoning behind the new API.

For pending support for Node 13 in the 5.x branch, see #348.

If you run into any problems feel free to report it here or in a new issue.

**Comment by yunabe** [comment]
Thank you for the update.

> The latest 6.0 beta release includes support for Node 13

`6.0.0-beta.2` is marked as `latest` and `npm install` now install the beta version.
Is it intentional?

**Comment by rolftimmermans** [comment]
Yes this is intentional. This mostly affects new users and new projects, given that existing projects are likely to have something like `"zeromq": "^5.1.0",` in their `package.json`. New projects definitely gain the most from using the new API. Contrary to appearances this beta has a (longish) history as https://github.com/rolftimmermans/zeromq-ng and it also fixes a number of bugs in the 4.x and 5.x ranges. Nevertheless, please report any issues you may find!

**Comment by yunabe** [comment]
Thank you for the information, Rolf. If it's intentional, it's fine to me. I was just surprised to see `yarn upgrade --latest` installs the beta version :smile:

Because it seems like v6 has breaking API changes and it would take some amount of time to test it in my environment. But I believe I can catch up the new API smoothly because we now have great documentations, also known as `.d.ts`. Thank you for the great improvement!
