### ISSUE TITLE
Not getting connect event all the time.

### ISSUE THREAD

**Issue by agirorn** [zeromq/zeromq.js#352]
I'm almost never get the `connect` event from the pub/sub sockets in the new **6.0.0-beta.2**. except when I log them to the console then they magically become active.

I have this test file to demonstrate the behavior that should be runnable from the root of the project.

**test.js**

> If you uncomment the EVENTS code then it works like a charm.
```js
const zmq = require('.');
const assert = require('assert');

const delay = (time) => new Promise((resolve) => setTimeout(resolve, time));
const pEvent = (o, e) => new Promise((resolve) => { o.on(e, resolve); });

const {
  XPublisher,
  Publisher,
  Subscriber,
  XSubscriber,
  Proxy,
} = zmq;

let proxy;

let reset;

const TIMEOUT = 8000;
const timeoutId = setTimeout(() => {
  console.log(new Error(`The test has timed out after ${TIMEOUT}`));
  reset();
  process.exit(1);
}, TIMEOUT);

const run = async () => {
  const xpub = new XPublisher();
  const xsub = new XSubscriber();
  proxy = new Proxy(xpub, xsub);
  await proxy.frontEnd.bind('tcp://*:3001');
  await proxy.backEnd.bind('tcp://*:3002');
  proxy.run();

  const pub = new Publisher();
  const sub = new Subscri

  // // Enable the code below an then everything works fine every time
  // const EVENTS = [
  //   'connect',
  // ].forEach((event) => {
  //   pub.events.on(event, (data) => { console.log(`PUB:${event} => `, data); });
  //   sub.events.on(event, (data) => { console.log(`SUB:${event} => `, data); });
  // });

  const accepted =  pEvent(pub.events, 'connect');
  const connected = pEvent(sub.events, 'connect');

  console.log('going to connect to proxy');
  process.nextTick(async () => {
    pub.connect('tcp://127.0.0.1:3002');
  })
  process.nextTick(async () => {
    sub.connect('tcp://127.0.0.1:3001');
  });
  sub.subscribe('some work');

  await Promise.all([connected, accepted]);
  const read = sub.receive();
  pub.send('some work');

  const [topic] = await read;
  assert.equal('some work', topic.toString());
  console.log('done');
}

reset = () => {
  proxy.terminate();
  clearTimeout(timeoutId);
};

run()
  .then((res) => {
    reset();
    return res;
  })
  .catch((err) => {
    reset();
    throw err;
  })
  .then((res) => {
    console.log('Everything is awesome!!!!!');
    return res;
  })
  .then(console.log, console.error);
```

**expected output** 
```shell
going to connect to proxy
done
Everything is awesome!!!!!
```

**actual output**
```shell
going to connect to proxy
Error: The test has timed out after 8000
    at Timeout._onTimeout (/home/agirorn/code-open-source/zeromq.js/test.js:21:15)
    at listOnTimeout (internal/timers.js:531:17)
```

**Comment by rolftimmermans** [comment]
Great catch! The additional event handler might add a delay which is probably the reason this does not work without logging. However, to demonstrate the underlying issue, you can add the following line right after `await Promise.all([connected, accepted]);`:

```
  await new Promise(setImmediate);
```

Seems like a bug to me, I'll try to hunt it down!

**Comment by rolftimmermans** [comment]
So the behaviour you are seeing is what is know as the "slow joiner syndrome" (explained here: http://zguide.zeromq.org/cs:chapter1).

What you probably thought, and what I definitely thought based on your example, is that the `"connect"` event would reliably indicate when published messages would be received at the other end (either through a proxy with XPUB-XSUB or with PUB-SUB directly). I dug into this some more and it seems the `"connect"` event is not enough to indicate that. Source here: https://grokbase.com/t/zeromq/zeromq-dev/1523hksbpc/meaning-of-zmq-event-connected

So essentially you are either going to have to accept that the subscriber may not receive all messages (acceptable in many real-world PUB-SUB scenarios), or you need another mechanism to synchronise the publisher & subscriber.

The reason the logging seemed to "fix" the issue is probably one of timing.

Please let me know if this makes sense and if you're able to solve your problem!

**Comment by agirorn** [comment]
I did some more testing on this and it seems to be the "slow joiner syndrome".

Thanks for looking into this and for all the work on the "Next Generation" module.
