### ISSUE TITLE
Dose not wait for connection.

### ISSUE THREAD

**Issue by agirorn** [zeromq/zeromq.js#355]
When trying to connect to a socket and the socket is not available the 6.0.0-beta.2 version does not keep the event loop busy while waiting for a connection, this can be tested white the code below.

**test.js**
```js
const {
  Publisher,
} = require('zeromq');

const pEvent = (events, event) => new Promise((resolve) => {
  events.on(event, resolve);
});

const run = async () => {
  const pub = new Publisher();

  const connected = pEvent(pub.events, 'connect');
  await pub.connect('tcp://127.0.0.1:60002');

  // // This will keep the event-loop bussy for ever.
  // setInterval(() => {
  //   if (pub.closed) {
  //     console.log('Connection has been closed;');
  //   }
  // }, 1000);

  await connected;
};

run()
  .then(() => {
    console.log('Got the connected event');
    process.exit(0);
  })
  .catch((error) => {
    console.log(error);
    process.exit(1);
  });
```

The previous version did keep the event loop bussy preventing the app from exiting.
Maybe it is just unclear to me who (My app or the zeromq module) should keep the node.js event loop busy while waiting for a connection to a socket.

I think it should be the responsibility of the module to keep the event loop active until I call [close()](http://zeromq.github.io/zeromq.js/classes/publisher.html#close) or [disconnect()](http://zeromq.github.io/zeromq.js/classes/publisher.html#disconnect) since I have asked it to connect and I'm waiting for a `connect` event,

**Comment by rolftimmermans** [comment]
Thanks for the report, I'll investigate!

**Comment by rolftimmermans** [comment]
While the socket itself keeps the event loop running, you can only see this in effect when you are actually using the socket. You should be able to observe this, for example, if you change the socket to a `Subscriber` and add a `sub.receive()` (intentionally without `await`) just before `await connected`. The call to `receive()` will not succeed because no messages can be read until the socket is connected, and the process won't terminate.

It seems a bit of an edge case to use the socket event observer via `socket.events`, but to not use the socket itself. However I do agree that the process should be kept alive, which is something that the event observer itself currently doesn't do.

I think I have a fix for this available, but I need to do a bit of testing to see if there are no downsides.

Hopefully the workaround of actually using the socket is sufficient for now; I'll keep this open until the fix lands.
