### ISSUE TITLE
statically defined NAPI_VERSION 4

### ISSUE THREAD

**Issue by russaa** [zeromq/zeromq.js#370]
**Describe the bug**
building fails if the target requires N-API 3 (or lower), since `binding.gyp` defines `'NAPI_VERSION=4'` statically

**Reproducing**
rebuild for `node` or `electron` version that requires N-API 3, e.g.
```
node-gyp rebuild --target=10.11.0
```

the first error for this is something like (followed by many more)
```
napi.h(2104): error C2061: syntax error: identifier 'napi_threadsafe_function' (compiling source file ..\src\context.cc)
```

But after modifying `binding.gyp` by setting `'NAPI_VERSION=3'`, the above command successfully compiles `zeromq.lib`

**Expected behavior**
the N-API version should be detected in correspondence to the [N-API Version Matrix](https://nodejs.org/docs/latest/api/n-api.html#n_api_n_api_version_matrix), and the pre-compiler variable `NAPI_VERSION` be set accordingly

Or the N-API version should be settable via command-line arguments & should be documented.

**Tested on**
 - OS: Windows 10 / MinGW
 - ZeroMQ.js version: 6.0.0-beta.5

**Comment by rolftimmermans** [comment]
I *think* we can lower the requirement to N-API 3 given that we don't support Node 8 with the 6.x releases anymore, but I'll have to double-check.

**Comment by russaa** [comment]
I find the N-API Version Matrix somewhat confusing, but as far as I understood it, it means something like:  
 * N-API vX applies to the Node version starting with the entry, up until the version of the next entry to the right
 * if there is no next entry on the right, then up to the version of the left-most entry in the next row

which would mean that the N-API version can actually __decrease__ when the major version number of Node is incremented

For instance, N-API v4 applies to Node 8.16.0 - 8.16.2, and Node 9.0.0 starts again with N-API v1

So mapping a Node version to a N-API version is not straight forward ...

The simplest solution would be, I think, to make the N-API version setting configurable & document it, so that the library can be compiled to other targets if need be

**Comment by rolftimmermans** [comment]
Alright, the minimum supported version is now 10.2, with N-API 3. That means the prebuilds in the next release should also work with Node 10.2+.

In general you can't just change the N-API version because it indicates the lowest version that has all required library features. N-API 3 was problematic because it had features added to it gradually. Which is why the minimum version was set to N-API 4. But since we don't support Node.js 8.x anymore the problematic versions are now limited to Node.js 10.1/10.2 and we can just indicate this easily in the package.json version requirement..
