### ISSUE TITLE
Can't specify the `routingId` when the socket is set to IMMEDIATE

### ISSUE THREAD

**Issue by Sceat** [zeromq/zeromq.js#392]
**Describe the bug**
When connecting to a tcp address with a zmq Stream socket, we can't write anymore due to the loss of the routingId

**Reproducing**
```js
import zmq from 'zeromq'

async function main() {
  const server = new zmq.Stream()
  const client = new zmq.Stream({ immediate: true })
  await server.bind('tcp://0.0.0.0:3000')
  client.connect('tcp://0.0.0.0:3000', { routingId: 'foo' })
  await client.send(['foo', 'hello world'])
}
main()
```

**Expected behavior**
I expect to be able to send a msg, it works without `immediate`

**Tested on**
 - OS: `arch`
 - ZeroMQ.js version: `6.0.0-beta.2`

> if i actually call `receive` before to extract the key then it works

```js
import zmq from 'zeromq'

async function main() {
  const server = new zmq.Stream()
  const client = new zmq.Stream({ immediate: true })
  await server.bind('tcp://0.0.0.0:3000')
  client.connect('tcp://0.0.0.0:3000', { routingId: 'foo' })
  const [key] = await client.receive()
  await client.send([key, 'hello world'])
}
main()
```

**Comment by rolftimmermans** [comment]
When looking at the code in libzmq this seems intentional; from what I can see is that creation of a pipe is delayed until the connection is established, and that code path uses a generated ID rather than the given routing ID.

If you want to know more about this it might be worth opening an issue with the [libzmq](https://github.com/zeromq/libzmq) repository.

What particular reason do you have to use `immediate: true` on a `Stream` socket?

**Comment by Sceat** [comment]
Actually i have no idea as i can't remember the stuff i was working on at that time lol :/

**Comment by rolftimmermans** [comment]
Alright, I'll close this then. If this becomes a problem again for you I suggest to open a new issue at https://github.com/zeromq/libzmq.
