### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by DonJayamanne** [zeromq/zeromq.js#442]
Thanks for this great package.
Not sure whether this is the right place for the question of of this has been answered.
I'm curious about the state of this project. It's been a while since this was last updated.

Are there no more plans to maintain this or are the maintainers looking for community contributions to keep this project alive?

Thanks again for this project

**Comment by aminya** [comment]
I fixed many of the issues in #444. If I could get access to NPM, I could release v6.

**Comment by flowck** [comment]
@rolftimmermans I've seen your name in the latest commits, can you help us understand what's the status of the project? Is there anyone leading the development on this project?

Thanks in advance.

**Comment by rolftimmermans** [comment]
Last time I worked on this project version 6 was feature complete and ready for prime time. Due to unrelated circumstances I have stopped using ZeroMQ since then.

I'd be happy to answer any questions anyone may have about the implementation. I don't have the proper permissions to appoint any new maintainers, though.

**Comment by aminya** [comment]
@rolftimmermans Thanks. Do you know anyone who can merge #444?

**Comment by aminya** [comment]
I got access to this repository. I plan to merge #444 and then try to debug the memory leak issues (which seems to cause the GC tests to fail as well). Any help would be appreciated!
