### ISSUE TITLE
Publishing v5 with the included prebuilds on npm

### ISSUE THREAD

**Issue by aminya** [zeromq/zeromq.js#451]
I was finally able to fix the build issues for v5 by switching to GitHub Actions and prebuildify. I used my personal account to publish ZeroMQ for Hydrogen, but we should also release an official version.

The process for publishing described here:
https://github.com/zeromq/zeromq.js/blob/5.x/CONTRIBUTING.md#releasing-a-new-npm-version

**Comment by albertowd** [comment]
Do you think this update could be changed the way the lib is compiled? Since yesterday my x86 builds cannot be compiled anymore, the last useful version I can compile is 5.2.0. My x64 compilations are still working as expected.

This are my x86 compile logs:
[5.2.0-ia32.log](https://github.com/zeromq/zeromq.js/files/6320682/5.2.0-ia32.log)
[5.2.1-ia32.log](https://github.com/zeromq/zeromq.js/files/6320683/5.2.1-ia32.log)
[5.2.4-ia32.log](https://github.com/zeromq/zeromq.js/files/6320684/5.2.4-ia32.log)

**Comment by aminya** [comment]
@albertowd I will release a new version with the prebuilds included and then you check if the error still presits. The latest released version is kind of fauly as it doesn't include any prebuilds.

**Comment by aminya** [comment]
OK, this is fixed now. 5.2.6 was released with the included prebuilds

**Comment by albertowd** [comment]
Ok, but now I'm having another problem: the prebuilds are working on a node environment, but not after I've created an .exe and copy the correct prebuild.node to the folder:

Error: No native build was found for platform=win32 arch=ia32 runtime=node abi=72 uv=1 libc=glibc node=12.18.1
    loaded from: C:\snapshot\channel-agent\node_modules\zeromq

**Comment by aminya** [comment]
Node-gyp-build relies on the location of the `prebuilds` folder. You shouldn't move those. Also, in case you use a bundler, declare ZeroMQ as external so it is not bundled [because of this issue](https://github.com/prebuild/node-gyp-build/issues/22).
