### ISSUE TITLE
Upgrade to libzmq 4.2 on Linux

### ISSUE THREAD

**Issue by lgeiger** [zeromq/zeromq.js#94]
The prebuilt binaries fail on [Travis CI](https://travis-ci.org/nteract/zmq-prebuilt-testing/builds/171694110) with the following error when trying to require them:
```
/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/travis/build/nteract/zmq-prebuilt-testing/node_modules/zeromq/build/Release/zmq.node)
```
I guess this is cause by the upgrade to libzmq 4.2.0

[Stack overflow](http://stackoverflow.com/questions/35392310/error-building-gcc-4-8-3-from-source-libstdc-so-6-version-cxxabi-1-3-8-not) tells us:
> So, this problem occurs when a library that has been built with a newer compiler is linked with an older version of C++ library - or sometimes when a newer headerfile is used to compile something that then links to an older C++ library.
It is also possible come up with a similar problem when moving binary files from one system to another, if the shared libraries installed on the "new system" are older than the ones on which the code was built.
There are typically three plausible solutions: 1. Recompile the offending library with an older compiler. 2. Install a newever version of the C++ library. 3. Rebuild the C++ library from sources (with a new enough compiler).

We built the binaries with gcc 4.9 so this could be the problem. The strange thing is that it worked for `v3.0.0`.

Should we try to build with gcc 4.8 or earlier? I have no idea if this would fix it.

**Comment by rgbkrk** [comment]
Might as well give it a shot and then test locally?

We can also revert to the previous version of libzmq for now (making sure to post an issue in libzmq about it).

**Comment by lgeiger** [comment]
For now we fixed it by reverting to libzmq 4.1.6 on Linux.
`v3.1.1` is already published.

**Comment by rgbkrk** [comment]
This is fixed now right?

**Comment by interpretor** [comment]
As described in http://gcc.gnu.org/onlinedocs/libstdc++/faq.html#faq.how_to_set_paths, we could set the library path for the Travis-CI job, so it can require the correct lib.

**Comment by lgeiger** [comment]
@interpretor Thanks for investigating!

I don't think setting the library path specific for Travis is a option for us. The problem is not so much that Travis fails. For it to pass we just need to include the same compiler that were used for generating the prebuilt binaries.
We rather want our prebuilts to be usable regardless of what compiler is installed. That's why we have the [`prebuilt-testing`](https://github.com/zeromq/zeromq.js/tree/prebuilt-testing) branch that tests our latest release on CI systems without C++ build tooling installed. It is this build that failed after upgrading libzmq to 4.2.0 on Linux.

I don't know why it works with libzmq 4.1.6 and not with 4.2.x but we might want to look into statically linking `libstdc++`.
That said I have very little experience with C++ compiler details so I might be totally wrong about that.

**Comment by interpretor** [comment]
Ok, I didn't know that you want to achieve compatibility regardless of the distribution.
So for me it looks like the simple solution is to use an older compiler than 4.9. (I would recommend 4.6, as this is an old enough compiler to cover most of the distributions used at the moment)

**Comment by lgeiger** [comment]
>So for me it looks like the simple solution is to use an older compiler than 4.9. (I would recommend 4.6, as this is an old enough compiler to cover most of the distributions used at the moment)

Sure, want to give that a try?

**Comment by interpretor** [comment]
Sorry for the duplicate pull request, I made a mistake at pushing the correct HEAD.

We have a problem now: `gcc-4.8` (with CXXABI_1.3.7) is the oldest version we can use with the current NAN, because it needs C++11 support.
So I fear that the prebuilt-testing will fail on the Travis-CI machine, because Travis uses the no longer maintained Ubuntu 12.04, which ships `gcc-4.6` (CXXABI_1.3.5) per default. (https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html)
So I think we have two options now:
- Statically link the `libstdc++` and use the compiler of our choice (you already mentioned that)
- Only support current supported distributions, which have at least `gcc-4.8` installed (Ubuntu 14.04, Debian 8)

The second option would be my choice, as I don't see the need to support prebuilds for unmaintained distributions. If someone would really need the binding, he is free to compile it by himself.
Travis-CI has the ability to use Ubuntu 14.04 LTS (https://docs.travis-ci.com/user/ci-environment/), so we could edit the Travis-CI job.
